### ISSUE TITLE
pls help me build 

### ISSUE THREAD

**Issue by vtnplus** [goacoincore/goacoin#1]
I have problem on ubuntu
CXX      script/libbitcoin_common_a-standard.o
  CXX      libbitcoin_common_a-spork.o
  AR       libbitcoin_common.a
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      support/libbitcoin_util_a-pagelocker.o
  CXX      libbitcoin_util_a-chainparamsbase.o
/bin/bash: ../share/genbuild.sh: Permission denied
Makefile:9589: recipe for target 'obj/build.h' failed
make[2]: *** [obj/build.h] Error 126
make[2]: Leaving directory '/home/admin/CoinBuilds/goacoin/src'
Makefile:9080: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/admin/CoinBuilds/goacoin/src'
Makefile:652: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

What i need fix

**Comment by goacoincore** [comment]
try
chmod 755 /home/admin/CoinBuilds/goacoin/share/genbuild.sh

**Comment by vtnplus** [comment]
thanks. i try

**Comment by vtnplus** [comment]
thanks develop
my pool start 
https://miner.mpool.us/ my pool

**Comment by vtnplus** [comment]
hi master. what i need do it {"result":{"error":"Incorrect key."},"method":"balance"} ?

**Comment by goacoincore** [comment]
Use "getbalance"
