### ISSUE TITLE
Masternode "status": "WATCHDOG_EXPIRED"

### ISSUE THREAD

**Issue by Gonzo19844** [goacoincore/goacoin#9]
I have all time the error "status": "WATCHDOG_EXPIRED"
we need sential for the goacoin wallet can you set it please

**Comment by goacoincore** [comment]
First check your master using the command
./goacoin-cli masternode status

Despite status of the "WATCHDOG_EXPIRED" node works and receives reward.

This be solved after transition most of participants to new version wallet.
